# Generated by Django 5.2.9 on 2025-12-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='blogs/')),
                ('short_desc', models.TextField()),
                ('full_content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
