# Generated by Django 5.2.9 on 2026-01-06 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_alter_country_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='slug',
        ),
    ]
