# Generated by Django 5.2.9 on 2026-01-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_remove_country_name_remove_country_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='place1_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='place1_image',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
        migrations.AddField(
            model_name='country',
            name='place1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='place2_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='place2_image',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
        migrations.AddField(
            model_name='country',
            name='place2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='place3_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='place3_image',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
        migrations.AddField(
            model_name='country',
            name='place3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='place4_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='place4_image',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
        migrations.AddField(
            model_name='country',
            name='place4_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
