# Generated by Django 5.2.9 on 2026-01-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_country_place1_description_country_place1_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
