# Generated by Django 5.2.9 on 2026-01-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='countries/'),
        ),
    ]
