# Generated by Django 5.2.9 on 2026-01-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_country_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='cover_image',
            field=models.ImageField(upload_to='countries/'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
