# Generated by Django 5.2.9 on 2026-01-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_alter_country_cover_image_alter_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='country',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='countries/'),
        ),
    ]
