# Generated by Django 5.2.9 on 2026-01-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0019_booking_refund_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='refund_amount',
        ),
    ]
