# Generated by Django 5.2.9 on 2026-01-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0020_remove_booking_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Pending', 'Pending'), ('Refunded', 'Refunded')], default='Not Applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
