# Generated by Django 5.2.9 on 2026-01-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0022_booking_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
