# Generated by Django 5.2.9 on 2026-01-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0023_booking_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='Hault_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='food_services',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='mode_of_travelling',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='supervisor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
