# Generated by Django 5.2.9 on 2026-01-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0025_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
    ]
