# Generated by Django 5.1.4 on 2026-02-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0028_booking_booking_status_contactmessage_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
