# Generated by Django 5.2.9 on 2026-02-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0029_alter_country_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='refunded_at',
            new_name='refund_requested_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_requested',
            field=models.BooleanField(default=False),
        ),
    ]
