# Generated by Django 5.1.4 on 2026-03-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0034_booking_address_alter_booking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.URLField(blank=True, help_text='Enter image URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_screenshot',
            field=models.URLField(blank=True, help_text='Enter payment screenshot URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='screenshot',
            field=models.URLField(blank=True, help_text='Enter screenshot URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='cover_image',
            field=models.URLField(blank=True, help_text='Enter cover image URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='place1_image',
            field=models.URLField(blank=True, help_text='Enter place1 image URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='place2_image',
            field=models.URLField(blank=True, help_text='Enter place2 image URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='place3_image',
            field=models.URLField(blank=True, help_text='Enter place3 image URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='place4_image',
            field=models.URLField(blank=True, help_text='Enter place4 image URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.URLField(blank=True, help_text='Enter image URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.URLField(blank=True, help_text='Enter image URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='image',
            field=models.URLField(blank=True, help_text='Enter absolute image URL', max_length=500, null=True),
        ),
    ]
