# Generated by Django 5.1.4 on 2026-03-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.URLField(blank=True, help_text='Enter image URL', max_length=500, null=True),
        ),
    ]
