# Generated by Django 5.1.4 on 2025-12-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_travelnews_published_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsArticle',
        ),
    ]
